import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';
import { z } from 'zod';

// .env lives at the repo root, one level above backend/.
//
// `override: true` is deliberate and important. Developer shells commonly
// export a DATABASE_URL for whatever project they last worked on, and dotenv's
// default is to leave existing process.env values alone — so this repo's .env
// would be silently ignored and migrations would run against someone else's
// database. The file on disk always wins; to point at a different database,
// edit .env or pass DATABASE_URL explicitly to the command.
//
// `.env.local` is loaded afterwards and wins, following the Vercel convention:
// it is machine-generated by `vercel env pull` / the Marketplace integrations,
// so it holds the real provisioned credentials, while `.env` holds the
// hand-maintained local defaults.
const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '../..');
dotenv.config({ path: path.join(repoRoot, '.env'), override: true });
dotenv.config({ path: path.join(repoRoot, '.env.local'), override: true });

const booleanish = z
  .enum(['0', '1', 'true', 'false', ''])
  .default('0')
  .transform((value) => value === '1' || value === 'true');

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: z.coerce.number().int().min(1).max(65535).default(3001),
  HOST: z.string().default('127.0.0.1'),
  LOG_LEVEL: z.enum(['fatal', 'error', 'warn', 'info', 'debug', 'trace', 'silent']).default('info'),
  /**
   * Comma-separated origins allowed to call the API cross-origin, e.g. a
   * frontend deployed to a CDN. Empty means same-origin only.
   */
  CORS_ORIGINS: z.string().default(''),
  /**
   * Shared secret for the scheduled-sync endpoint. Vercel sends it as
   * `Authorization: Bearer $CRON_SECRET` on cron invocations; without it the
   * endpoint is a public "resync everything" button.
   */
  CRON_SECRET: z.string().optional(),
  /** Set by Vercel on every deployment; absent when running as a normal server. */
  VERCEL: z.string().optional(),

  DATABASE_URL: z.string().min(1, 'DATABASE_URL is required — run `npm run db:up` and copy .env.example'),
  /**
   * The direct (session-mode) endpoint, where a provider exposes it separately
   * from a pooled DATABASE_URL. Preferred when present — see `databaseUrl`.
   */
  DATABASE_URL_UNPOOLED: z.string().optional(),
  TEST_DATABASE_URL: z.string().optional(),

  IONOS_API_KEY: z.string().optional(),
  IONOS_TENANT_ID: z.string().optional(),
  IONOS_BASE_URL: z.string().url().default('https://api.hosting.ionos.com/domains'),

  /**
   * GoDaddy signs requests with a key *and* a secret, joined as
   * `sso-key <key>:<secret>`. Both are secret; only the key's name is stored in
   * `registrar_accounts.credential_ref`, with the secret resolved by convention
   * in the registry.
   */
  GODADDY_API_KEY: z.string().optional(),
  GODADDY_API_SECRET: z.string().optional(),
  /** X-Shopper-Id, for a reseller acting on a subaccount. Not a secret. */
  GODADDY_SHOPPER_ID: z.string().optional(),
  /** Point at https://api.ote-godaddy.com for the OTE sandbox. */
  GODADDY_BASE_URL: z.string().url().default('https://api.godaddy.com'),

  /** Parallel per-domain detail fetches during a full sync, for any registrar. */
  REGISTRAR_CONCURRENCY: z.coerce.number().int().min(1).max(16).optional(),
  /** Deprecated alias for REGISTRAR_CONCURRENCY, kept so existing .env files work. */
  IONOS_CONCURRENCY: z.coerce.number().int().min(1).max(16).default(4),

  MOCK_REGISTRAR: booleanish,
  MOCK_FAILURE_MODE: z.enum(['429', '401', 'partial', 'slow', '']).default(''),
  DEBUG_REGISTRAR: booleanish,

  RESEND_API_KEY: z.string().optional(),
  ALERT_EMAIL_TO: z.string().optional(),
  ALERT_EMAIL_FROM: z.string().optional(),
});

function load() {
  const parsed = envSchema.safeParse(process.env);
  if (!parsed.success) {
    const issues = parsed.error.issues
      .map((issue) => `  ${issue.path.join('.') || '(root)'}: ${issue.message}`)
      .join('\n');
    // Fail fast and loudly: a half-configured server that boots and then throws
    // on the first request is far harder to diagnose than this.
    console.error(`Invalid environment configuration:\n${issues}\n`);
    process.exit(1);
  }
  return parsed.data;
}

export const env = load();

export type Env = typeof env;

/**
 * Origins permitted to call the API from a browser.
 *
 * Empty by default, which means same-origin only — the right answer when the
 * backend serves the bundle itself. Populate it when the frontend lives on a
 * different origin; an explicit list rather than `*` because these responses
 * carry the whole portfolio.
 */
export const corsOrigins: string[] = env.CORS_ORIGINS.split(',')
  .map((origin) => origin.trim().replace(/\/+$/, ''))
  .filter(Boolean);

/**
 * The connection string the app actually uses.
 *
 * Prefers the direct (session-mode) endpoint when a provider offers both.
 * Managed Postgres is usually fronted by PgBouncer in transaction mode, which
 * does not keep a client on one server connection between statements — so
 * session-level advisory locks silently stop providing mutual exclusion.
 * Verified against a live pooled provider: through the pooler two separate
 * clients both succeed at `pg_try_advisory_lock` on the same key; through the
 * direct endpoint the second correctly fails.
 *
 * Sync exclusion depends on exactly that lock, so a pooled connection would let
 * two syncs reconcile the same account at once. This app opens a handful of
 * connections for one user, so the direct endpoint costs nothing.
 */
export const databaseUrl = env.DATABASE_URL_UNPOOLED ?? env.DATABASE_URL;

/**
 * How many per-domain detail requests a full sync runs in parallel.
 *
 * Was `IONOS_CONCURRENCY` when IONOS was the only adapter; that name is still
 * honoured as the fallback rather than breaking every existing `.env`.
 */
export const registrarConcurrency = env.REGISTRAR_CONCURRENCY ?? env.IONOS_CONCURRENCY;

/** True when we should talk to fixtures rather than a real registrar API. */
export const isMockMode = env.MOCK_REGISTRAR;

export const isProduction = env.NODE_ENV === 'production';

/**
 * True when running as a Vercel function rather than a long-lived process.
 *
 * Three things have to behave differently there: in-process cron cannot run
 * (nothing survives between invocations), background work after a response
 * must be handed to the platform, and the connection pool has to stay small
 * because each instance opens its own.
 */
export const isServerless = Boolean(env.VERCEL);
