import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';
import { z } from 'zod';

// .env lives at the repo root, one level above backend/.
//
// `override: true` is deliberate and important. Developer shells commonly
// export a DATABASE_URL for whatever project they last worked on, and dotenv's
// default is to leave existing process.env values alone — so this repo's .env
// would be silently ignored and migrations would run against someone else's
// database. The file on disk always wins; to point at a different database,
// edit .env or pass DATABASE_URL explicitly to the command.
//
// `.env.local` is loaded afterwards and wins, following the Vercel convention:
// it is machine-generated by `vercel env pull` / the Marketplace integrations,
// so it holds the real provisioned credentials, while `.env` holds the
// hand-maintained local defaults.
const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '../..');
dotenv.config({ path: path.join(repoRoot, '.env'), override: true });
dotenv.config({ path: path.join(repoRoot, '.env.local'), override: true });

const booleanish = z
  .enum(['0', '1', 'true', 'false', ''])
  .default('0')
  .transform((value) => value === '1' || value === 'true');

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: z.coerce.number().int().min(1).max(65535).default(3001),
  HOST: z.string().default('127.0.0.1'),
  LOG_LEVEL: z.enum(['fatal', 'error', 'warn', 'info', 'debug', 'trace', 'silent']).default('info'),

  DATABASE_URL: z.string().min(1, 'DATABASE_URL is required — run `npm run db:up` and copy .env.example'),
  /**
   * Set by the Neon Marketplace integration alongside a pooled DATABASE_URL.
   * Preferred when present — see `databaseUrl` below.
   */
  DATABASE_URL_UNPOOLED: z.string().optional(),
  TEST_DATABASE_URL: z.string().optional(),

  IONOS_API_KEY: z.string().optional(),
  IONOS_TENANT_ID: z.string().optional(),
  IONOS_BASE_URL: z.string().url().default('https://api.hosting.ionos.com/domains'),
  IONOS_CONCURRENCY: z.coerce.number().int().min(1).max(16).default(4),

  MOCK_REGISTRAR: booleanish,
  MOCK_FAILURE_MODE: z.enum(['429', '401', 'partial', 'slow', '']).default(''),
  DEBUG_REGISTRAR: booleanish,

  RESEND_API_KEY: z.string().optional(),
  ALERT_EMAIL_TO: z.string().optional(),
  ALERT_EMAIL_FROM: z.string().optional(),
});

function load() {
  const parsed = envSchema.safeParse(process.env);
  if (!parsed.success) {
    const issues = parsed.error.issues
      .map((issue) => `  ${issue.path.join('.') || '(root)'}: ${issue.message}`)
      .join('\n');
    // Fail fast and loudly: a half-configured server that boots and then throws
    // on the first request is far harder to diagnose than this.
    console.error(`Invalid environment configuration:\n${issues}\n`);
    process.exit(1);
  }
  return parsed.data;
}

export const env = load();

export type Env = typeof env;

/**
 * The connection string the app actually uses.
 *
 * Prefers the direct (unpooled) endpoint when a provider offers both. Neon's
 * pooled endpoint is PgBouncer in transaction mode, which does not keep a
 * client on one server connection between statements — so session-level
 * advisory locks silently stop providing mutual exclusion. Verified against a
 * live Neon database: on the pooled URL two separate clients both succeed at
 * `pg_try_advisory_lock` on the same key; on the direct URL the second
 * correctly fails.
 *
 * Sync exclusion depends on exactly that lock, so a pooled connection would let
 * two syncs reconcile the same account at once. This app opens a handful of
 * connections for one user, so the direct endpoint costs nothing.
 */
export const databaseUrl = env.DATABASE_URL_UNPOOLED ?? env.DATABASE_URL;

/** True when we should talk to fixtures rather than a real registrar API. */
export const isMockMode = env.MOCK_REGISTRAR;

export const isProduction = env.NODE_ENV === 'production';
